# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

resources:
  pipelines:
  - pipeline: tech-arti-blogs.js-e2e-express-server    # Name of the pipeline resource
    source: tech-arti-blogs.pipelines-javascript-docker # Name of the pipeline referenced by the pipeline resource
    project: Configuring Pipeline # Required only if the source pipeline is in another project
    trigger: true # enable the trigger

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
